name: docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Install minimal toolchain
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              override: true
              profile: minimal
    
          - uses: Swatinem/rust-cache@v2
    
          - name: Run rustdoc
            env:
              RUSTDOCFLAGS: -D warnings
            uses: actions-rs/cargo@v1
            with:
              command: doc
              args: --no-deps --document-private-items